/**
 * Authoritative NEET / JEE syllabus chapter lists.
 * key  → used as chapter_key in DB (stable slug)
 * name → human-readable chapter name
 */

export const SYLLABUS = {
  'NEET': {
    Biology: [
      // Class 11
      { key: 'bio-living-world',          name: 'The Living World',                     class: '11' },
      { key: 'bio-bio-classification',    name: 'Biological Classification',            class: '11' },
      { key: 'bio-plant-kingdom',         name: 'Plant Kingdom',                        class: '11' },
      { key: 'bio-animal-kingdom',        name: 'Animal Kingdom',                       class: '11' },
      { key: 'bio-morphology-plants',     name: 'Morphology of Flowering Plants',       class: '11' },
      { key: 'bio-anatomy-plants',        name: 'Anatomy of Flowering Plants',          class: '11' },
      { key: 'bio-structural-animals',    name: 'Structural Organisation in Animals',   class: '11' },
      { key: 'bio-cell-unit-of-life',     name: 'Cell: The Unit of Life',               class: '11' },
      { key: 'bio-biomolecules',          name: 'Biomolecules',                         class: '11' },
      { key: 'bio-cell-cycle',            name: 'Cell Cycle and Cell Division',         class: '11' },
      { key: 'bio-transport-plants',      name: 'Transport in Plants',                  class: '11' },
      { key: 'bio-mineral-nutrition',     name: 'Mineral Nutrition',                    class: '11' },
      { key: 'bio-photosynthesis',        name: 'Photosynthesis in Higher Plants',      class: '11' },
      { key: 'bio-respiration-plants',    name: 'Respiration in Plants',                class: '11' },
      { key: 'bio-plant-growth',          name: 'Plant Growth and Development',         class: '11' },
      { key: 'bio-digestion',             name: 'Digestion and Absorption',             class: '11' },
      { key: 'bio-breathing',             name: 'Breathing and Exchange of Gases',      class: '11' },
      { key: 'bio-body-fluids',           name: 'Body Fluids and Circulation',          class: '11' },
      { key: 'bio-excretory-products',    name: 'Excretory Products and Elimination',   class: '11' },
      { key: 'bio-locomotion',            name: 'Locomotion and Movement',              class: '11' },
      { key: 'bio-neural-control',        name: 'Neural Control and Coordination',      class: '11' },
      { key: 'bio-chemical-coordination', name: 'Chemical Coordination and Integration',class: '11' },
      // Class 12
      { key: 'bio-reproduction-organisms',name: 'Reproduction in Organisms',            class: '12' },
      { key: 'bio-sexual-reproduction',   name: 'Sexual Reproduction in Flowering Plants',class:'12'},
      { key: 'bio-human-reproduction',    name: 'Human Reproduction',                   class: '12' },
      { key: 'bio-reproductive-health',   name: 'Reproductive Health',                  class: '12' },
      { key: 'bio-inheritance',           name: 'Principles of Inheritance and Variation',class:'12'},
      { key: 'bio-molecular-basis',       name: 'Molecular Basis of Inheritance',       class: '12' },
      { key: 'bio-evolution',             name: 'Evolution',                            class: '12' },
      { key: 'bio-human-health',          name: 'Human Health and Disease',             class: '12' },
      { key: 'bio-food-production',       name: 'Strategies for Food Production',       class: '12' },
      { key: 'bio-microbes',              name: 'Microbes in Human Welfare',            class: '12' },
      { key: 'bio-biotech-principles',    name: 'Biotechnology: Principles and Processes',class:'12'},
      { key: 'bio-biotech-applications',  name: 'Biotechnology and its Applications',   class: '12' },
      { key: 'bio-organisms-populations', name: 'Organisms and Populations',            class: '12' },
      { key: 'bio-ecosystem',             name: 'Ecosystem',                            class: '12' },
      { key: 'bio-biodiversity',          name: 'Biodiversity and Conservation',        class: '12' },
      { key: 'bio-environmental-issues',  name: 'Environmental Issues',                 class: '12' },
    ],
    Physics: [
      { key: 'phy-physical-world',        name: 'Physical World and Measurement',       class: '11' },
      { key: 'phy-kinematics',            name: 'Kinematics',                           class: '11' },
      { key: 'phy-laws-of-motion',        name: 'Laws of Motion',                       class: '11' },
      { key: 'phy-work-energy',           name: 'Work, Energy and Power',               class: '11' },
      { key: 'phy-system-particles',      name: 'Motion of System of Particles',        class: '11' },
      { key: 'phy-gravitation',           name: 'Gravitation',                          class: '11' },
      { key: 'phy-bulk-matter',           name: 'Properties of Bulk Matter',            class: '11' },
      { key: 'phy-thermodynamics',        name: 'Thermodynamics',                       class: '11' },
      { key: 'phy-kinetic-theory',        name: 'Kinetic Theory of Gases',             class: '11' },
      { key: 'phy-oscillations-waves',    name: 'Oscillations and Waves',               class: '11' },
      { key: 'phy-electrostatics',        name: 'Electrostatics',                       class: '12' },
      { key: 'phy-current-electricity',   name: 'Current Electricity',                  class: '12' },
      { key: 'phy-magnetic-effects',      name: 'Magnetic Effects of Current & Magnetism',class:'12'},
      { key: 'phy-emi-ac',                name: 'EMI and Alternating Currents',         class: '12' },
      { key: 'phy-em-waves',              name: 'Electromagnetic Waves',                class: '12' },
      { key: 'phy-optics',                name: 'Optics',                               class: '12' },
      { key: 'phy-dual-nature',           name: 'Dual Nature of Radiation and Matter',  class: '12' },
      { key: 'phy-atoms-nuclei',          name: 'Atoms and Nuclei',                     class: '12' },
      { key: 'phy-electronic-devices',    name: 'Electronic Devices',                   class: '12' },
    ],
    Chemistry: [
      { key: 'chem-basic-concepts',       name: 'Some Basic Concepts of Chemistry',     class: '11' },
      { key: 'chem-structure-atom',       name: 'Structure of Atom',                    class: '11' },
      { key: 'chem-classification',       name: 'Classification of Elements & Periodicity',class:'11'},
      { key: 'chem-chemical-bonding',     name: 'Chemical Bonding and Molecular Structure',class:'11'},
      { key: 'chem-states-matter',        name: 'States of Matter',                     class: '11' },
      { key: 'chem-thermodynamics',       name: 'Chemical Thermodynamics',              class: '11' },
      { key: 'chem-equilibrium',          name: 'Equilibrium',                          class: '11' },
      { key: 'chem-redox',                name: 'Redox Reactions',                      class: '11' },
      { key: 'chem-hydrogen',             name: 'Hydrogen',                             class: '11' },
      { key: 'chem-s-block',              name: 'The s-Block Elements',                 class: '11' },
      { key: 'chem-p-block-1',            name: 'The p-Block Elements (Group 13 & 14)', class: '11' },
      { key: 'chem-organic-basics',       name: 'Organic Chemistry: Basic Principles',  class: '11' },
      { key: 'chem-hydrocarbons',         name: 'Hydrocarbons',                         class: '11' },
      { key: 'chem-environmental',        name: 'Environmental Chemistry',              class: '11' },
      { key: 'chem-solid-state',          name: 'Solid State',                          class: '12' },
      { key: 'chem-solutions',            name: 'Solutions',                            class: '12' },
      { key: 'chem-electrochemistry',     name: 'Electrochemistry',                     class: '12' },
      { key: 'chem-chemical-kinetics',    name: 'Chemical Kinetics',                    class: '12' },
      { key: 'chem-surface-chemistry',    name: 'Surface Chemistry',                    class: '12' },
      { key: 'chem-isolation-elements',   name: 'Isolation of Elements',                class: '12' },
      { key: 'chem-p-block-2',            name: 'The p-Block Elements (Group 15–18)',    class: '12' },
      { key: 'chem-d-f-block',            name: 'The d and f Block Elements',           class: '12' },
      { key: 'chem-coordination',         name: 'Coordination Compounds',               class: '12' },
      { key: 'chem-haloalkanes',          name: 'Haloalkanes and Haloarenes',           class: '12' },
      { key: 'chem-alcohols-phenols',     name: 'Alcohols, Phenols and Ethers',         class: '12' },
      { key: 'chem-aldehydes-ketones',    name: 'Aldehydes, Ketones and Carboxylic Acids',class:'12'},
      { key: 'chem-amines',               name: 'Organic Compounds with Nitrogen',      class: '12' },
      { key: 'chem-biomolecules',         name: 'Biomolecules',                         class: '12' },
      { key: 'chem-polymers',             name: 'Polymers',                             class: '12' },
      { key: 'chem-everyday-chemistry',   name: 'Chemistry in Everyday Life',           class: '12' },
    ],
  },
  'JEE Main': {
    Physics: [
      { key: 'jphy-units',                name: 'Units and Measurements',               class: '11' },
      { key: 'jphy-motion-1d',            name: 'Motion in a Straight Line',            class: '11' },
      { key: 'jphy-motion-plane',         name: 'Motion in a Plane',                    class: '11' },
      { key: 'jphy-laws-motion',          name: 'Laws of Motion',                       class: '11' },
      { key: 'jphy-work-energy',          name: 'Work, Energy and Power',               class: '11' },
      { key: 'jphy-particles-rigid',      name: 'System of Particles and Rotational Motion',class:'11'},
      { key: 'jphy-gravitation',          name: 'Gravitation',                          class: '11' },
      { key: 'jphy-bulk-matter',          name: 'Mechanical Properties of Solids & Fluids',class:'11'},
      { key: 'jphy-thermal-properties',  name: 'Thermal Properties of Matter',         class: '11' },
      { key: 'jphy-thermodynamics',       name: 'Thermodynamics',                       class: '11' },
      { key: 'jphy-kinetic-theory',       name: 'Kinetic Theory',                       class: '11' },
      { key: 'jphy-oscillations',         name: 'Oscillations',                         class: '11' },
      { key: 'jphy-waves',                name: 'Waves',                                class: '11' },
      { key: 'jphy-electrostatics',       name: 'Electric Charges and Fields',          class: '12' },
      { key: 'jphy-potential',            name: 'Electrostatic Potential and Capacitance',class:'12'},
      { key: 'jphy-current',              name: 'Current Electricity',                  class: '12' },
      { key: 'jphy-moving-charges',       name: 'Moving Charges and Magnetism',         class: '12' },
      { key: 'jphy-magnetism',            name: 'Magnetism and Matter',                 class: '12' },
      { key: 'jphy-emi',                  name: 'Electromagnetic Induction',            class: '12' },
      { key: 'jphy-ac',                   name: 'Alternating Current',                  class: '12' },
      { key: 'jphy-em-waves',             name: 'Electromagnetic Waves',                class: '12' },
      { key: 'jphy-ray-optics',           name: 'Ray Optics and Optical Instruments',   class: '12' },
      { key: 'jphy-wave-optics',          name: 'Wave Optics',                          class: '12' },
      { key: 'jphy-dual-nature',          name: 'Dual Nature of Radiation and Matter',  class: '12' },
      { key: 'jphy-atoms',                name: 'Atoms',                                class: '12' },
      { key: 'jphy-nuclei',               name: 'Nuclei',                               class: '12' },
      { key: 'jphy-semiconductors',       name: 'Semiconductor Electronics',            class: '12' },
    ],
    Chemistry: [
      { key: 'jchem-basic-concepts',      name: 'Some Basic Concepts of Chemistry',     class: '11' },
      { key: 'jchem-structure-atom',      name: 'Structure of Atom',                    class: '11' },
      { key: 'jchem-periodic',            name: 'Classification of Elements',           class: '11' },
      { key: 'jchem-bonding',             name: 'Chemical Bonding',                     class: '11' },
      { key: 'jchem-states',              name: 'States of Matter',                     class: '11' },
      { key: 'jchem-thermo',              name: 'Thermodynamics',                       class: '11' },
      { key: 'jchem-equilibrium',         name: 'Equilibrium',                          class: '11' },
      { key: 'jchem-redox',               name: 'Redox Reactions',                      class: '11' },
      { key: 'jchem-s-block',             name: 'Hydrogen & s-Block Elements',          class: '11' },
      { key: 'jchem-p-block-1',           name: 'p-Block Elements (Group 13 & 14)',     class: '11' },
      { key: 'jchem-organic-basics',      name: 'Organic Chemistry Basics',             class: '11' },
      { key: 'jchem-hydrocarbons',        name: 'Hydrocarbons',                         class: '11' },
      { key: 'jchem-solid-state',         name: 'Solid State',                          class: '12' },
      { key: 'jchem-solutions',           name: 'Solutions',                            class: '12' },
      { key: 'jchem-electrochemistry',    name: 'Electrochemistry',                     class: '12' },
      { key: 'jchem-kinetics',            name: 'Chemical Kinetics',                    class: '12' },
      { key: 'jchem-d-f-block',           name: 'The d and f Block Elements',           class: '12' },
      { key: 'jchem-coordination',        name: 'Coordination Compounds',               class: '12' },
      { key: 'jchem-p-block-2',           name: 'p-Block Elements (Group 15–18)',       class: '12' },
      { key: 'jchem-haloalkanes',         name: 'Haloalkanes and Haloarenes',           class: '12' },
      { key: 'jchem-alcohols',            name: 'Alcohols, Phenols and Ethers',         class: '12' },
      { key: 'jchem-carbonyl',            name: 'Aldehydes, Ketones, Carboxylic Acids', class: '12' },
      { key: 'jchem-amines',              name: 'Amines',                               class: '12' },
      { key: 'jchem-biomolecules',        name: 'Biomolecules and Polymers',            class: '12' },
    ],
    Mathematics: [
      { key: 'jmath-sets',                name: 'Sets and Functions',                   class: '11' },
      { key: 'jmath-algebra',             name: 'Algebra (Complex, Sequences)',         class: '11' },
      { key: 'jmath-coordinate',          name: 'Coordinate Geometry',                  class: '11' },
      { key: 'jmath-calculus-1',          name: 'Calculus — Limits and Derivatives',    class: '11' },
      { key: 'jmath-statistics',          name: 'Statistics and Probability',           class: '11' },
      { key: 'jmath-vectors-3d',          name: 'Vectors and 3D Geometry',              class: '12' },
      { key: 'jmath-matrices',            name: 'Matrices and Determinants',            class: '12' },
      { key: 'jmath-continuity',          name: 'Continuity and Differentiability',     class: '12' },
      { key: 'jmath-applications',        name: 'Applications of Derivatives',          class: '12' },
      { key: 'jmath-integrals',           name: 'Integrals',                            class: '12' },
      { key: 'jmath-diffeq',              name: 'Differential Equations',               class: '12' },
      { key: 'jmath-probability',         name: 'Probability',                          class: '12' },
      { key: 'jmath-linear-prog',         name: 'Linear Programming',                   class: '12' },
    ],
  },
};

// Get syllabus for a given exam type with null-safe fallback
export function getSyllabus(examType) {
  const t = examType ?? 'NEET';
  // Collapse all JEE variants; anything else (MHT-CET, unknown) falls back to NEET
  if (t === 'JEE' || t === 'JEE Advanced' || t === 'JEE Main') return SYLLABUS['JEE Main'];
  return SYLLABUS[t] ?? SYLLABUS['NEET'];
}

// Total chapter count
export function totalChapters(examType) {
  const s = getSyllabus(examType);
  if (!s) return 0;
  return Object.values(s).reduce((acc, chapters) => acc + chapters.length, 0);
}
