import { useNavigate } from 'react-router-dom';
import { ArrowLeft, FileText } from 'lucide-react';
import { PublicNavBar, PublicFooter } from '../components/layout/PublicChrome';
import { useSeo } from '../lib/seo';

const LAST_UPDATED = 'August 5, 2026';

function Section({ title, children }) {
  return (
    <div className="space-y-2">
      <h2 className="text-base font-bold text-slate-900">{title}</h2>
      <div className="text-sm text-slate-600 leading-relaxed space-y-2">{children}</div>
    </div>
  );
}

/**
 * Plain-language terms of service — a starting point for the business to
 * review/adapt, not a substitute for actual legal review.
 */
export default function TermsOfServicePage() {
  useSeo('/terms');
  const navigate = useNavigate();

  return (
    <div className="min-h-screen bg-slate-50 flex flex-col">
      <PublicNavBar />
      <div className="flex-1 py-10 px-4">
      <div className="max-w-2xl mx-auto space-y-8">
        <button
          onClick={() => navigate(-1)}
          className="flex items-center gap-1.5 text-sm text-slate-500 hover:text-slate-800 transition-colors"
        >
          <ArrowLeft size={14} /> Back
        </button>

        <div className="flex items-center gap-3">
          <div className="h-11 w-11 rounded-2xl bg-primary-50 flex items-center justify-center shrink-0">
            <FileText size={20} className="text-primary-600" />
          </div>
          <div>
            <h1 className="text-2xl font-extrabold text-slate-900">Terms of Service</h1>
            <p className="text-xs text-slate-400 mt-0.5">Last updated: {LAST_UPDATED}</p>
          </div>
        </div>

        <div className="card space-y-6">
          <Section title="Agreement to terms">
            <p>
              EaseWithExam ("EWE", "we", "us") is operated by Acenzos. By creating an account or using the
              platform, you agree to these terms. If you're under 18, please use EWE with a parent or
              guardian's awareness.
            </p>
          </Section>

          <Section title="What EWE provides">
            <p>AI-assisted exam preparation for NEET, JEE, and board students — practice questions, mock
              tests, an AI tutor, study plans, and analytics. Free and paid (Premium) plans are available; plan
              limits and features are shown on the Pricing page.</p>
          </Section>

          <Section title="Your account">
            <p>You're responsible for keeping your account credentials secure and for activity that happens
              under your account. Don't share your login, attempt to bypass usage limits, or use the platform
              to cheat during an actual exam.</p>
          </Section>

          <Section title="AI-generated content">
            <p>Practice questions, explanations, summaries, and answer-sheet evaluations are generated by AI and
              may occasionally be incorrect or incomplete. Use your judgement, and treat EWE as a study aid, not
              a substitute for your teachers or official exam-body materials.</p>
          </Section>

          <Section title="Payments & subscriptions">
            <p>Premium subscriptions are billed via Razorpay at the price shown at checkout. Subscriptions
              renew as described on the Pricing page; you can cancel future renewal at any time from your
              Profile. Refunds are handled per our{' '}
              <a href="/refund/" className="text-primary-600 hover:underline font-semibold">Refund Policy</a>.</p>
          </Section>

          <Section title="Acceptable use">
            <p>Don't misuse the platform: no scraping, reverse-engineering, reselling access, uploading content
              you don't have rights to, or attempting to disrupt the service for other students.</p>
          </Section>

          <Section title="Termination">
            <p>We may suspend or terminate accounts that violate these terms. You can stop using EWE and
              request account deletion at any time by contacting support.</p>
          </Section>

          <Section title="Changes to these terms">
            <p>We may update these terms as the product changes. Material changes will be reflected by updating
              the date at the top of this page.</p>
          </Section>

          <Section title="Contact">
            <p>Questions about these terms? Email{' '}
              <a href="mailto:info@acenzos.com" className="text-primary-600 hover:underline font-semibold">
                info@acenzos.com
              </a>.</p>
          </Section>
        </div>
      </div>
      </div>
      <PublicFooter />
    </div>
  );
}
