-- P0.5 batch: mutations — bind admin RPCs to a verified identity.
--
-- GENERATED by scripts/gen-p05-guards.mjs. Each function below is re-emitted
-- exactly as pg_get_functiondef() returned it, with a single line added after
-- the outer BEGIN:
--
--     perform assert_verified_admin(p_caller);  -- P0.5
--
-- Nothing else in any body changes. The pre-existing inline admins lookup is
-- left in place on purpose, so the diff is one statement per function.
--
-- assert_verified_admin() requires verified_uid() to be non-null, to equal
-- p_caller, and to be an active admin. That blocks anon-key callers (the live
-- bypass) and also blocks a signed-in non-admin passing a known admin UID,
-- which a grant-based gate could never do — and, unlike the P0 role gate, it
-- does not depend on the request arriving as `authenticated`. Every request in
-- this project arrives as `anon`; only auth.jwt() is populated.
--
-- Functions in this batch: 35
--   admin_add_coaching_student(text,uuid,jsonb)
--   admin_bulk_upsert_test_users(text,jsonb)
--   admin_clear_exam_blueprints(text)
--   admin_delete_coaching_assignment(text,uuid)
--   admin_delete_coaching_student(text,uuid)
--   admin_delete_onboarding_option(text,uuid)
--   admin_delete_paper_template(text,text)
--   admin_delete_published_test(text,uuid)
--   admin_delete_quota_override(text,text)
--   admin_delete_study_note(text,uuid)
--   admin_delete_test_assignment(text,uuid)
--   admin_delete_test_rows(text,text,text,text[])
--   admin_delete(text,text)
--   admin_grant_subscription(text,text,text,integer)
--   admin_publish_test(text,jsonb)
--   admin_reset_user_quota(text,text,text)
--   admin_seed_question_history(text,text[],jsonb)
--   admin_seed_weak_topics(text,text[],jsonb)
--   admin_send_notification(text,text,text,text,text,text,integer)
--   admin_set_platform_setting(text,text,text)
--   admin_set_quota_config(text,text,integer,integer,integer,integer,integer,integer)
--   admin_set_quota_override(text,text,integer,integer,integer,text,text,integer,integer,integer)
--   admin_toggle_feature_flag(text,text,boolean)
--   admin_upsert_coaching_assignment(text,uuid,uuid,jsonb)
--   admin_upsert_coaching_centre(text,uuid,jsonb)
--   admin_upsert_exam_category(text,uuid,text,text,text,text,text,text,text[],integer)
--   admin_upsert_onboarding_option(text,uuid,text,text,text[],text,text,text,text,integer,boolean,boolean,boolean,text,text[])
--   admin_upsert_paper_template(text,text,integer,integer,integer,jsonb)
--   admin_upsert_plan_config(text,text,text,text,integer,text,text,jsonb,jsonb,boolean)
--   admin_upsert_study_note(text,uuid,text,text,text,text,text,text,uuid,boolean,text[],text,integer,integer,integer,text)
--   admin_upsert_syllabus_node(text,text,text,text,text,text,integer,jsonb,uuid)
--   admin_upsert_test_assignment(text,jsonb,uuid)
--   admin_upsert(text,text,text,text,text,text)
--   coaching_admin_delete(text,text)
--   coaching_admin_upsert(text,text,text,text,uuid,text)

begin;


-- ── admin_add_coaching_student(text,uuid,jsonb) ─────────────────
CREATE OR REPLACE FUNCTION public.admin_add_coaching_student(p_caller text, p_centre_id uuid, p_fields jsonb)
 RETURNS coaching_students
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare v_role text; v_row coaching_students;
begin
  perform assert_verified_admin(p_caller);  -- P0.5
  select role into v_role from admins where uid = p_caller and is_active = true;
  if v_role is null or v_role not in ('superadmin','admin') then raise exception 'Access denied'; end if;
  insert into coaching_students (centre_id, firebase_uid, name, email, target_exam, student_name, student_email, batch)
  values (p_centre_id, p_fields->>'firebase_uid', p_fields->>'name', p_fields->>'email',
          p_fields->>'target_exam', p_fields->>'student_name', p_fields->>'student_email', p_fields->>'batch')
  returning * into v_row;
  return v_row;
end; $function$;

-- ── admin_bulk_upsert_test_users(text,jsonb) ────────────────────
CREATE OR REPLACE FUNCTION public.admin_bulk_upsert_test_users(p_caller text, p_rows jsonb)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare v_role text;
begin
  perform assert_verified_admin(p_caller);  -- P0.5
  select role into v_role from admins where uid = p_caller and is_active = true;
  if v_role is null or v_role not in ('superadmin','admin') then raise exception 'Access denied'; end if;
  insert into public.users (firebase_uid, display_name, email, target_exam, syllabus, class_level, onboarding_completed, auth_method)
  select
    r->>'firebase_uid', r->>'display_name', r->>'email', r->>'target_exam',
    r->>'syllabus', r->>'class_level',
    coalesce((r->>'onboarding_completed')::boolean, true),
    coalesce(r->>'auth_method', 'google')
  from jsonb_array_elements(p_rows) r
  on conflict (firebase_uid) do update set
    display_name = excluded.display_name, email = excluded.email,
    target_exam = excluded.target_exam, syllabus = excluded.syllabus,
    class_level = excluded.class_level;
end; $function$;

-- ── admin_clear_exam_blueprints(text) ───────────────────────────
CREATE OR REPLACE FUNCTION public.admin_clear_exam_blueprints(p_caller text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN

  perform assert_verified_admin(p_caller);  -- P0.5
  IF NOT EXISTS(SELECT 1 FROM admins WHERE uid = p_caller AND is_active = true) THEN
    RAISE EXCEPTION 'Not authorized';
  END IF;
  DELETE FROM exam_blueprints;
END;
$function$;

-- ── admin_delete_coaching_assignment(text,uuid) ─────────────────
CREATE OR REPLACE FUNCTION public.admin_delete_coaching_assignment(p_caller text, p_id uuid)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare v_role text;
begin
  perform assert_verified_admin(p_caller);  -- P0.5
  select role into v_role from admins where uid = p_caller and is_active = true;
  if v_role is null or v_role not in ('superadmin','admin') then raise exception 'Access denied'; end if;
  delete from coaching_assignments where id = p_id;
end; $function$;

-- ── admin_delete_coaching_student(text,uuid) ────────────────────
CREATE OR REPLACE FUNCTION public.admin_delete_coaching_student(p_caller text, p_id uuid)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare v_role text;
begin
  perform assert_verified_admin(p_caller);  -- P0.5
  select role into v_role from admins where uid = p_caller and is_active = true;
  if v_role is null or v_role not in ('superadmin','admin') then raise exception 'Access denied'; end if;
  delete from coaching_students where id = p_id;
end; $function$;

-- ── admin_delete_onboarding_option(text,uuid) ───────────────────
CREATE OR REPLACE FUNCTION public.admin_delete_onboarding_option(p_caller text, p_id uuid)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare v_role text;
begin
  perform assert_verified_admin(p_caller);  -- P0.5
  select role into v_role from admins where uid = p_caller and is_active = true;
  if v_role is null or v_role not in ('superadmin','admin') then raise exception 'Access denied'; end if;
  delete from onboarding_category_display where id = p_id;
end;
$function$;

-- ── admin_delete_paper_template(text,text) ──────────────────────
CREATE OR REPLACE FUNCTION public.admin_delete_paper_template(p_caller text, p_exam_type text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN

  perform assert_verified_admin(p_caller);  -- P0.5
  IF NOT EXISTS (SELECT 1 FROM admins WHERE uid = p_caller AND is_active = true) THEN
    RAISE EXCEPTION 'Not authorized';
  END IF;
  DELETE FROM paper_templates WHERE exam_type = p_exam_type;
END;
$function$;

-- ── admin_delete_published_test(text,uuid) ──────────────────────
CREATE OR REPLACE FUNCTION public.admin_delete_published_test(p_caller text, p_id uuid)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin

  perform assert_verified_admin(p_caller);  -- P0.5
  if not public.is_active_admin(p_caller) then
    raise exception 'Access denied';
  end if;
  delete from public.published_tests where id = p_id;
end;
$function$;

-- ── admin_delete_quota_override(text,text) ──────────────────────
CREATE OR REPLACE FUNCTION public.admin_delete_quota_override(p_caller text, p_user_id text)
 RETURNS json
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE v_role TEXT;
BEGIN
  perform assert_verified_admin(p_caller);  -- P0.5
  SELECT role INTO v_role FROM admins WHERE uid = p_caller AND is_active = true;
  IF v_role IS NULL OR v_role NOT IN ('superadmin','admin') THEN RAISE EXCEPTION 'Access denied'; END IF;
  DELETE FROM quota_overrides WHERE user_id = p_user_id;
  RETURN json_build_object('ok', true);
END;
$function$;

-- ── admin_delete_study_note(text,uuid) ──────────────────────────
CREATE OR REPLACE FUNCTION public.admin_delete_study_note(p_caller text, p_id uuid)
 RETURNS json
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE v_role TEXT;
BEGIN
  perform assert_verified_admin(p_caller);  -- P0.5
  SELECT role INTO v_role FROM admins WHERE uid = p_caller AND is_active = true;
  IF v_role IS NULL OR v_role NOT IN ('superadmin','admin') THEN RAISE EXCEPTION 'Access denied'; END IF;
  DELETE FROM study_notes WHERE id = p_id;
  RETURN json_build_object('ok', true);
END;
$function$;

-- ── admin_delete_test_assignment(text,uuid) ─────────────────────
CREATE OR REPLACE FUNCTION public.admin_delete_test_assignment(p_caller text, p_id uuid)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin

  perform assert_verified_admin(p_caller);  -- P0.5
  if not public.is_active_admin(p_caller) then
    raise exception 'Access denied';
  end if;
  delete from public.test_assignments where id = p_id;
  if not found then
    raise exception 'assignment % not found', p_id;
  end if;
end;
$function$;

-- ── admin_delete_test_rows(text,text,text,text[]) ───────────────
CREATE OR REPLACE FUNCTION public.admin_delete_test_rows(p_caller text, p_table text, p_col text, p_values text[])
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare v_role text;
begin
  perform assert_verified_admin(p_caller);  -- P0.5
  select role into v_role from admins where uid = p_caller and is_active = true;
  if v_role is null or v_role not in ('superadmin','admin') then raise exception 'Access denied'; end if;

  if p_table not in (
    'question_history', 'user_weak_topics', 'user_gamification',
    'daily_usage_quota', 'flashcards', 'notification_prefs', 'users',
    'coaching_centres'
  ) then
    raise exception 'Table not allowed for this operation';
  end if;
  if p_col not in ('user_id', 'firebase_uid', 'name') then
    raise exception 'Column not allowed for this operation';
  end if;

  execute format('delete from public.%I where %I = any($1)', p_table, p_col) using p_values;
end; $function$;

-- ── admin_delete(text,text) ─────────────────────────────────────
CREATE OR REPLACE FUNCTION public.admin_delete(p_caller text, p_target_uid text)
 RETURNS json
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
  v_caller_role TEXT;
  v_target_role TEXT;
BEGIN
  perform assert_verified_admin(p_caller);  -- P0.5
  SELECT role INTO v_caller_role FROM admins WHERE uid = p_caller AND is_active = true;
  IF v_caller_role IS DISTINCT FROM 'superadmin' THEN
    RETURN json_build_object('error', 'Unauthorized');
  END IF;
  IF p_caller = p_target_uid THEN
    RETURN json_build_object('error', 'Cannot delete your own account');
  END IF;
  SELECT role INTO v_target_role FROM admins WHERE uid = p_target_uid;
  IF v_target_role = 'superadmin' THEN
    RETURN json_build_object('error', 'Cannot delete another superadmin');
  END IF;
  DELETE FROM admins WHERE uid = p_target_uid;
  RETURN json_build_object('ok', true);
END;
$function$;

-- ── admin_grant_subscription(text,text,text,integer) ────────────
CREATE OR REPLACE FUNCTION public.admin_grant_subscription(p_caller text, p_user_id text, p_plan text, p_days integer DEFAULT 30)
 RETURNS json
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE v_role TEXT;
BEGIN
  perform assert_verified_admin(p_caller);  -- P0.5
  SELECT role INTO v_role FROM admins WHERE uid = p_caller AND is_active = true;
  IF v_role IS NULL OR v_role NOT IN ('superadmin','admin') THEN RAISE EXCEPTION 'Access denied'; END IF;

  INSERT INTO subscriptions (user_id, plan, status, starts_at, expires_at, updated_at)
  VALUES (p_user_id, p_plan, 'active', NOW(), NOW() + (p_days||' days')::INTERVAL, NOW())
  ON CONFLICT (user_id) DO UPDATE SET
    plan       = EXCLUDED.plan,
    status     = 'active',
    starts_at  = NOW(),
    expires_at = NOW() + (p_days||' days')::INTERVAL,
    updated_at = NOW();

  RETURN json_build_object('ok', true);
END;
$function$;

-- ── admin_publish_test(text,jsonb) ──────────────────────────────
CREATE OR REPLACE FUNCTION public.admin_publish_test(p_caller text, p_fields jsonb)
 RETURNS published_tests
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_row public.published_tests;
  v_created_by text;
  v_user_id text;
begin
  perform assert_verified_admin(p_caller);  -- P0.5
  if not public.is_active_admin(p_caller) then
    raise exception 'Access denied';
  end if;

  v_created_by := coalesce(p_fields->>'created_by', 'admin');
  v_user_id := nullif(p_fields->>'user_id', '');
  if v_created_by = 'student' and v_user_id is null then
    raise exception 'student-owned published tests must include user_id';
  end if;

  insert into public.published_tests (
    title, subject, exam_type, difficulty, questions,
    duration_minutes, is_published, question_count,
    blueprint_match_pct, created_by, user_id
  ) values (
    p_fields->>'title', p_fields->>'subject', p_fields->>'exam_type', p_fields->>'difficulty',
    coalesce(p_fields->'questions', '[]'::jsonb),
    (p_fields->>'duration_minutes')::int, true,
    coalesce(jsonb_array_length(coalesce(p_fields->'questions', '[]'::jsonb)), 0),
    (p_fields->>'blueprint_match_pct')::numeric, v_created_by, v_user_id
  ) returning * into v_row;

  return v_row;
end;
$function$;

-- ── admin_reset_user_quota(text,text,text) ──────────────────────
CREATE OR REPLACE FUNCTION public.admin_reset_user_quota(p_caller text, p_user_id text, p_date text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN

  perform assert_verified_admin(p_caller);  -- P0.5
  IF NOT EXISTS (SELECT 1 FROM admins WHERE uid = p_caller AND is_active = true) THEN
    RAISE EXCEPTION 'Unauthorized';
  END IF;
  DELETE FROM daily_usage_quota
  WHERE user_id = p_user_id AND usage_date = p_date::DATE;
END;
$function$;

-- ── admin_seed_question_history(text,text[],jsonb) ──────────────
CREATE OR REPLACE FUNCTION public.admin_seed_question_history(p_caller text, p_uids text[], p_rows jsonb)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare v_role text;
begin
  perform assert_verified_admin(p_caller);  -- P0.5
  select role into v_role from admins where uid = p_caller and is_active = true;
  if v_role is null or v_role not in ('superadmin','admin') then raise exception 'Access denied'; end if;

  delete from public.question_history where user_id = any(p_uids);

  insert into public.question_history (
    user_id, question_id, question_text, subject, topic, question_type,
    is_correct, source, due_date, ease_factor, interval_days, repetitions, is_mastered
  )
  select
    r->>'user_id', r->>'question_id', r->>'question_text', r->>'subject', r->>'topic',
    r->>'question_type', (r->>'is_correct')::boolean, r->>'source',
    (r->>'due_date')::date, (r->>'ease_factor')::real, (r->>'interval_days')::int,
    (r->>'repetitions')::int, (r->>'is_mastered')::boolean
  from jsonb_array_elements(p_rows) r;
end; $function$;

-- ── admin_seed_weak_topics(text,text[],jsonb) ───────────────────
CREATE OR REPLACE FUNCTION public.admin_seed_weak_topics(p_caller text, p_uids text[], p_rows jsonb)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare v_role text;
begin
  perform assert_verified_admin(p_caller);  -- P0.5
  select role into v_role from admins where uid = p_caller and is_active = true;
  if v_role is null or v_role not in ('superadmin','admin') then raise exception 'Access denied'; end if;

  delete from public.user_weak_topics where user_id = any(p_uids);

  insert into public.user_weak_topics (user_id, subject, topic, wrong_count, total_attempts, accuracy_pct, last_seen)
  select
    r->>'user_id', r->>'subject', r->>'topic',
    (r->>'wrong_count')::int, (r->>'total_attempts')::int, (r->>'accuracy_pct')::int, (r->>'last_seen')::date
  from jsonb_array_elements(p_rows) r;
end; $function$;

-- ── admin_send_notification(text,text,text,text,text,text,integer) 
CREATE OR REPLACE FUNCTION public.admin_send_notification(p_caller text, p_title text, p_body text, p_type text DEFAULT 'info'::text, p_user_id text DEFAULT NULL::text, p_url text DEFAULT NULL::text, p_expires_in_days integer DEFAULT NULL::integer)
 RETURNS json
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE v_role TEXT; v_expires TIMESTAMPTZ;
BEGIN
  perform assert_verified_admin(p_caller);  -- P0.5
  SELECT role INTO v_role FROM admins WHERE uid = p_caller AND is_active = true;
  IF v_role IS NULL OR v_role NOT IN ('superadmin','admin') THEN RAISE EXCEPTION 'Access denied'; END IF;
  IF p_expires_in_days IS NOT NULL THEN
    v_expires := NOW() + (p_expires_in_days||' days')::INTERVAL;
  END IF;
  INSERT INTO in_app_notifications (user_id, title, body, type, url, expires_at)
  VALUES (p_user_id, p_title, p_body, p_type, p_url, v_expires);
  RETURN json_build_object('ok', true);
END;
$function$;

-- ── admin_set_platform_setting(text,text,text) ──────────────────
CREATE OR REPLACE FUNCTION public.admin_set_platform_setting(p_caller text, p_key text, p_value text)
 RETURNS json
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE v_role TEXT;
BEGIN
  perform assert_verified_admin(p_caller);  -- P0.5
  SELECT role INTO v_role FROM admins WHERE uid = p_caller AND is_active = true;
  IF v_role IS NULL OR v_role NOT IN ('superadmin','admin') THEN RAISE EXCEPTION 'Access denied'; END IF;
  INSERT INTO platform_settings (key, value, updated_by, updated_at)
  VALUES (p_key, p_value, p_caller, NOW())
  ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value, updated_by = EXCLUDED.updated_by, updated_at = NOW();
  RETURN json_build_object('ok', true);
END;
$function$;

-- ── admin_set_quota_config(text,text,integer,integer,integer,integer,integer,integer) 
CREATE OR REPLACE FUNCTION public.admin_set_quota_config(p_caller text, p_plan_id text, p_ai integer, p_veda integer, p_mock integer, p_paper_evaluations integer DEFAULT NULL::integer, p_podcasts integer DEFAULT NULL::integer, p_paper_generations integer DEFAULT NULL::integer)
 RETURNS json
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE v_role TEXT;
BEGIN
  perform assert_verified_admin(p_caller);  -- P0.5
  SELECT role INTO v_role FROM admins WHERE uid = p_caller AND is_active = true;
  IF v_role IS NULL OR v_role NOT IN ('superadmin','admin') THEN RAISE EXCEPTION 'Access denied'; END IF;
  INSERT INTO quota_config (plan_id, ai_questions, veda_messages, mock_tests, paper_evaluations, podcasts, paper_generations)
  VALUES (p_plan_id, p_ai, p_veda, p_mock, p_paper_evaluations, p_podcasts, p_paper_generations)
  ON CONFLICT (plan_id) DO UPDATE SET
    ai_questions      = EXCLUDED.ai_questions,
    veda_messages     = EXCLUDED.veda_messages,
    mock_tests        = EXCLUDED.mock_tests,
    paper_evaluations = EXCLUDED.paper_evaluations,
    podcasts          = EXCLUDED.podcasts,
    paper_generations = EXCLUDED.paper_generations;
  RETURN json_build_object('ok', true);
END;
$function$;

-- ── admin_set_quota_override(text,text,integer,integer,integer,text,text,integer,integer,integer) 
CREATE OR REPLACE FUNCTION public.admin_set_quota_override(p_caller text, p_user_id text, p_ai integer DEFAULT NULL::integer, p_veda integer DEFAULT NULL::integer, p_mock integer DEFAULT NULL::integer, p_reason text DEFAULT NULL::text, p_expires_at text DEFAULT NULL::text, p_paper_evaluations integer DEFAULT NULL::integer, p_podcasts integer DEFAULT NULL::integer, p_paper_generations integer DEFAULT NULL::integer)
 RETURNS json
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE v_role TEXT; v_expires TIMESTAMPTZ;
BEGIN
  perform assert_verified_admin(p_caller);  -- P0.5
  SELECT role INTO v_role FROM admins WHERE uid = p_caller AND is_active = true;
  IF v_role IS NULL OR v_role NOT IN ('superadmin','admin') THEN RAISE EXCEPTION 'Access denied'; END IF;
  IF p_expires_at IS NOT NULL AND p_expires_at <> '' THEN
    v_expires := p_expires_at::TIMESTAMPTZ;
  END IF;
  INSERT INTO quota_overrides (user_id, ai_questions, veda_messages, mock_tests, reason, expires_at, updated_at, paper_evaluations, podcasts, paper_generations)
  VALUES (p_user_id, p_ai, p_veda, p_mock, p_reason, v_expires, NOW(), p_paper_evaluations, p_podcasts, p_paper_generations)
  ON CONFLICT (user_id) DO UPDATE SET
    ai_questions      = EXCLUDED.ai_questions,
    veda_messages     = EXCLUDED.veda_messages,
    mock_tests        = EXCLUDED.mock_tests,
    reason            = EXCLUDED.reason,
    expires_at        = EXCLUDED.expires_at,
    updated_at        = NOW(),
    paper_evaluations = EXCLUDED.paper_evaluations,
    podcasts          = EXCLUDED.podcasts,
    paper_generations = EXCLUDED.paper_generations;
  RETURN json_build_object('ok', true);
END;
$function$;

-- ── admin_toggle_feature_flag(text,text,boolean) ────────────────
CREATE OR REPLACE FUNCTION public.admin_toggle_feature_flag(p_caller text, p_key text, p_enabled boolean)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN

  perform assert_verified_admin(p_caller);  -- P0.5
  IF NOT EXISTS (
    SELECT 1 FROM admins WHERE uid = p_caller AND is_active = true
  ) THEN
    RAISE EXCEPTION 'unauthorized';
  END IF;

  INSERT INTO feature_flags (key, enabled)
  VALUES (p_key, p_enabled)
  ON CONFLICT (key) DO UPDATE SET enabled = EXCLUDED.enabled;
END;
$function$;

-- ── admin_upsert_coaching_assignment(text,uuid,uuid,jsonb) ──────
CREATE OR REPLACE FUNCTION public.admin_upsert_coaching_assignment(p_caller text, p_centre_id uuid, p_id uuid DEFAULT NULL::uuid, p_fields jsonb DEFAULT '{}'::jsonb)
 RETURNS coaching_assignments
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare v_role text; v_row coaching_assignments;
begin
  perform assert_verified_admin(p_caller);  -- P0.5
  select role into v_role from admins where uid = p_caller and is_active = true;
  if v_role is null or v_role not in ('superadmin','admin') then raise exception 'Access denied'; end if;

  if p_id is null then
    insert into coaching_assignments (centre_id, title, exam_type, subject, due_date, questions, description)
    values (p_centre_id, p_fields->>'title', p_fields->>'exam_type', p_fields->>'subject',
            (p_fields->>'due_date')::date, coalesce(p_fields->'questions', '[]'::jsonb), p_fields->>'description')
    returning * into v_row;
  else
    update coaching_assignments set
      title = coalesce(p_fields->>'title', title),
      exam_type = coalesce(p_fields->>'exam_type', exam_type),
      subject = coalesce(p_fields->>'subject', subject),
      due_date = coalesce((p_fields->>'due_date')::date, due_date),
      questions = coalesce(p_fields->'questions', questions),
      description = coalesce(p_fields->>'description', description),
      updated_at = now()
    where id = p_id and centre_id = p_centre_id
    returning * into v_row;
  end if;
  return v_row;
end; $function$;

-- ── admin_upsert_coaching_centre(text,uuid,jsonb) ───────────────
CREATE OR REPLACE FUNCTION public.admin_upsert_coaching_centre(p_caller text, p_id uuid DEFAULT NULL::uuid, p_fields jsonb DEFAULT '{}'::jsonb)
 RETURNS coaching_centres
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare v_role text; v_row coaching_centres;
begin
  perform assert_verified_admin(p_caller);  -- P0.5
  select role into v_role from admins where uid = p_caller and is_active = true;
  if v_role is null or v_role not in ('superadmin','admin') then raise exception 'Access denied'; end if;
  if p_id is null then
    insert into coaching_centres select * from jsonb_populate_record(null::coaching_centres, p_fields) returning * into v_row;
  else
    update coaching_centres set
      name = coalesce(p_fields->>'name', name),
      city = coalesce(p_fields->>'city', city),
      contact_email = coalesce(p_fields->>'contact_email', contact_email),
      contact_phone = coalesce(p_fields->>'contact_phone', contact_phone),
      plan = coalesce(p_fields->>'plan', plan),
      max_students = coalesce((p_fields->>'max_students')::int, max_students),
      status = coalesce(p_fields->>'status', status),
      notes = coalesce(p_fields->>'notes', notes),
      brand_color = coalesce(p_fields->>'brand_color', brand_color),
      website_url = coalesce(p_fields->>'website_url', website_url),
      phone = coalesce(p_fields->>'phone', phone),
      tagline = coalesce(p_fields->>'tagline', tagline),
      updated_at = now()
    where id = p_id
    returning * into v_row;
  end if;
  return v_row;
end; $function$;

-- ── admin_upsert_exam_category(text,uuid,text,text,text,text,text,text,text[],integer) 
CREATE OR REPLACE FUNCTION public.admin_upsert_exam_category(p_caller text, p_id uuid, p_exam_key text, p_label text, p_category_kind text, p_board_key text, p_class_key text, p_group_label text, p_subjects text[], p_sort_order integer)
 RETURNS exam_categories
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
  v_row exam_categories;
BEGIN
  perform assert_verified_admin(p_caller);  -- P0.5
  IF NOT EXISTS(SELECT 1 FROM admins WHERE uid = p_caller AND is_active = true) THEN
    RAISE EXCEPTION 'Not authorized';
  END IF;

  IF p_id IS NULL THEN
    INSERT INTO exam_categories (exam_key, label, category_kind, board_key, class_key, group_label, subjects, sort_order)
    VALUES (p_exam_key, p_label, p_category_kind, p_board_key, p_class_key, p_group_label, COALESCE(p_subjects, '{}'), COALESCE(p_sort_order, 0))
    ON CONFLICT (exam_key) DO UPDATE SET
      label = EXCLUDED.label, category_kind = EXCLUDED.category_kind, board_key = EXCLUDED.board_key,
      class_key = EXCLUDED.class_key, group_label = EXCLUDED.group_label, subjects = EXCLUDED.subjects,
      sort_order = EXCLUDED.sort_order, is_active = true, updated_at = now()
    RETURNING * INTO v_row;
  ELSE
    UPDATE exam_categories SET
      exam_key = p_exam_key, label = p_label, category_kind = p_category_kind,
      board_key = p_board_key, class_key = p_class_key, group_label = p_group_label,
      subjects = COALESCE(p_subjects, '{}'), sort_order = COALESCE(p_sort_order, 0), updated_at = now()
    WHERE id = p_id
    RETURNING * INTO v_row;
  END IF;

  RETURN v_row;
END;
$function$;

-- ── admin_upsert_onboarding_option(text,uuid,text,text,text[],text,text,text,text,integer,boolean,boolean,boolean,text,text[]) 
CREATE OR REPLACE FUNCTION public.admin_upsert_onboarding_option(p_caller text, p_id uuid, p_option_type text, p_option_key text, p_category_keys text[], p_title text, p_description text, p_icon_name text, p_color text, p_sort_order integer, p_is_active boolean, p_needs_board boolean DEFAULT false, p_needs_class boolean DEFAULT false, p_default_class_level text DEFAULT NULL::text, p_allowed_class_levels text[] DEFAULT '{}'::text[])
 RETURNS onboarding_category_display
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare v_role text; v_row onboarding_category_display;
begin
  perform assert_verified_admin(p_caller);  -- P0.5
  select role into v_role from admins where uid = p_caller and is_active = true;
  if v_role is null or v_role not in ('superadmin','admin') then raise exception 'Access denied'; end if;

  insert into onboarding_category_display (
    id, option_type, option_key, category_keys, title, description,
    icon_name, color, sort_order, is_active, needs_board, needs_class,
    default_class_level, allowed_class_levels, updated_at
  )
  values (
    coalesce(p_id, gen_random_uuid()), p_option_type, p_option_key, p_category_keys,
    p_title, p_description, p_icon_name, p_color, p_sort_order, p_is_active,
    p_needs_board, p_needs_class, p_default_class_level, coalesce(p_allowed_class_levels, '{}'), now()
  )
  on conflict (id) do update set
    option_type = excluded.option_type, option_key = excluded.option_key,
    category_keys = excluded.category_keys, title = excluded.title,
    description = excluded.description, icon_name = excluded.icon_name,
    color = excluded.color, sort_order = excluded.sort_order,
    is_active = excluded.is_active, needs_board = excluded.needs_board,
    needs_class = excluded.needs_class, default_class_level = excluded.default_class_level,
    allowed_class_levels = excluded.allowed_class_levels,
    updated_at = now()
  returning * into v_row;

  return v_row;
end;
$function$;

-- ── admin_upsert_paper_template(text,text,integer,integer,integer,jsonb) 
CREATE OR REPLACE FUNCTION public.admin_upsert_paper_template(p_caller text, p_exam_type text, p_total_questions integer, p_duration_minutes integer, p_total_marks integer, p_sections jsonb)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN

  perform assert_verified_admin(p_caller);  -- P0.5
  IF NOT EXISTS (SELECT 1 FROM admins WHERE uid = p_caller AND is_active = true) THEN
    RAISE EXCEPTION 'Not authorized';
  END IF;

  INSERT INTO paper_templates (exam_type, total_questions, duration_minutes, total_marks, sections, updated_at)
  VALUES (p_exam_type, p_total_questions, p_duration_minutes, p_total_marks, p_sections, now())
  ON CONFLICT (exam_type) DO UPDATE SET
    total_questions  = EXCLUDED.total_questions,
    duration_minutes = EXCLUDED.duration_minutes,
    total_marks      = EXCLUDED.total_marks,
    sections         = EXCLUDED.sections,
    updated_at       = now();
END;
$function$;

-- ── admin_upsert_plan_config(text,text,text,text,integer,text,text,jsonb,jsonb,boolean) 
CREATE OR REPLACE FUNCTION public.admin_upsert_plan_config(p_caller text, p_plan_id text, p_name text, p_price_label text, p_price_paise integer, p_description text, p_badge text, p_features jsonb, p_locked jsonb, p_active boolean)
 RETURNS plan_config
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
  v_row plan_config;
BEGIN
  perform assert_verified_admin(p_caller);  -- P0.5
  IF NOT EXISTS(SELECT 1 FROM admins WHERE uid = p_caller AND is_active = true) THEN
    RAISE EXCEPTION 'Not authorized';
  END IF;

  INSERT INTO plan_config (plan_id, name, price_label, price_paise, description, badge, features, locked, active)
  VALUES (p_plan_id, p_name, p_price_label, COALESCE(p_price_paise, 0), p_description, p_badge,
          COALESCE(p_features, '[]'::jsonb), COALESCE(p_locked, '[]'::jsonb), COALESCE(p_active, true))
  ON CONFLICT (plan_id) DO UPDATE SET
    name = EXCLUDED.name, price_label = EXCLUDED.price_label, price_paise = EXCLUDED.price_paise,
    description = EXCLUDED.description, badge = EXCLUDED.badge, features = EXCLUDED.features,
    locked = EXCLUDED.locked, active = EXCLUDED.active, updated_at = now()
  RETURNING * INTO v_row;

  RETURN v_row;
END;
$function$;

-- ── admin_upsert_study_note(text,uuid,text,text,text,text,text,text,uuid,boolean,text[],text,integer,integer,integer,text) 
CREATE OR REPLACE FUNCTION public.admin_upsert_study_note(p_caller text, p_id uuid DEFAULT NULL::uuid, p_title text DEFAULT ''::text, p_subject text DEFAULT NULL::text, p_exam_type text DEFAULT NULL::text, p_chapter text DEFAULT NULL::text, p_content text DEFAULT NULL::text, p_pdf_url text DEFAULT NULL::text, p_centre_id uuid DEFAULT NULL::uuid, p_is_published boolean DEFAULT false, p_tags text[] DEFAULT '{}'::text[], p_unit text DEFAULT NULL::text, p_page_start integer DEFAULT NULL::integer, p_page_end integer DEFAULT NULL::integer, p_sort_order integer DEFAULT 0, p_source_text text DEFAULT NULL::text)
 RETURNS json
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE v_role TEXT; v_id UUID; result JSON;
BEGIN
  perform assert_verified_admin(p_caller);  -- P0.5
  SELECT role INTO v_role FROM admins WHERE uid = p_caller AND is_active = true;
  IF v_role IS NULL OR v_role NOT IN ('superadmin','admin') THEN RAISE EXCEPTION 'Access denied'; END IF;

  IF p_id IS NOT NULL THEN
    UPDATE study_notes SET
      title = p_title, subject = p_subject, exam_type = p_exam_type,
      chapter = p_chapter, content = p_content, pdf_url = p_pdf_url,
      centre_id = p_centre_id, is_published = p_is_published,
      tags = p_tags, unit = p_unit, page_start = p_page_start,
      page_end = p_page_end, sort_order = p_sort_order,
      source_text = p_source_text, updated_at = NOW()
    WHERE id = p_id RETURNING id INTO v_id;
  ELSE
    INSERT INTO study_notes
      (title, subject, exam_type, chapter, content, pdf_url, centre_id, is_published, tags, created_by, unit, page_start, page_end, sort_order, source_text)
    VALUES (p_title, p_subject, p_exam_type, p_chapter, p_content, p_pdf_url, p_centre_id, p_is_published, p_tags, p_caller, p_unit, p_page_start, p_page_end, p_sort_order, p_source_text)
    RETURNING id INTO v_id;
  END IF;

  SELECT row_to_json(n) INTO result FROM study_notes n WHERE n.id = v_id;
  RETURN result;
END;
$function$;

-- ── admin_upsert_syllabus_node(text,text,text,text,text,text,integer,jsonb,uuid) 
CREATE OR REPLACE FUNCTION public.admin_upsert_syllabus_node(p_caller text, p_exam_type text, p_subject text, p_chapter_name text, p_chapter_key text, p_class_level text DEFAULT NULL::text, p_sort_order integer DEFAULT 1, p_subtopics jsonb DEFAULT '[]'::jsonb, p_id uuid DEFAULT NULL::uuid)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_row syllabus_nodes%ROWTYPE;
BEGIN
  perform assert_verified_admin(p_caller);  -- P0.5
  IF NOT EXISTS (SELECT 1 FROM admins WHERE uid = p_caller AND is_active = true) THEN
    RAISE EXCEPTION 'unauthorized';
  END IF;

  IF p_id IS NOT NULL THEN
    UPDATE syllabus_nodes SET
      chapter_name = p_chapter_name,
      sort_order   = p_sort_order,
      subtopics    = p_subtopics,
      is_active    = true
    WHERE id = p_id
    RETURNING * INTO v_row;
  ELSE
    INSERT INTO syllabus_nodes
      (exam_type, subject, chapter_key, chapter_name, class_level, sort_order, subtopics)
    VALUES
      (p_exam_type, p_subject, p_chapter_key, p_chapter_name, p_class_level, p_sort_order, p_subtopics)
    ON CONFLICT (exam_type, subject, chapter_key) DO UPDATE SET
      chapter_name = EXCLUDED.chapter_name,
      sort_order   = EXCLUDED.sort_order,
      subtopics    = EXCLUDED.subtopics
    RETURNING * INTO v_row;
  END IF;

  RETURN row_to_json(v_row)::jsonb;
END;
$function$;

-- ── admin_upsert_test_assignment(text,jsonb,uuid) ───────────────
CREATE OR REPLACE FUNCTION public.admin_upsert_test_assignment(p_caller text, p_fields jsonb, p_id uuid DEFAULT NULL::uuid)
 RETURNS test_assignments
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_row public.test_assignments;
  v_test_id uuid;
  v_assigned_to_user_uid text;
  v_target_exam text;
  v_target_syllabus text;
  v_target_class_level text;
  v_note text;
begin
  perform assert_verified_admin(p_caller);  -- P0.5
  if not public.is_active_admin(p_caller) then
    raise exception 'Access denied';
  end if;

  v_assigned_to_user_uid := nullif(p_fields->>'assigned_to_user_uid', '');
  v_target_exam := nullif(p_fields->>'target_exam', '');
  v_target_syllabus := nullif(p_fields->>'target_syllabus', '');
  v_target_class_level := nullif(p_fields->>'target_class_level', '');
  v_note := nullif(p_fields->>'note', '');

  if p_id is null then
    v_test_id := (p_fields->>'test_id')::uuid;
    if v_test_id is null then
      raise exception 'test_id is required';
    end if;
    if v_assigned_to_user_uid is null and v_target_exam is null
       and v_target_syllabus is null and v_target_class_level is null then
      raise exception 'at least one assignment target is required';
    end if;

    insert into public.test_assignments (
      created_by, test_id, assigned_to_user_uid,
      target_exam, target_syllabus, target_class_level,
      is_active, expires_at, note
    ) values (
      p_caller, v_test_id, v_assigned_to_user_uid,
      v_target_exam, v_target_syllabus, v_target_class_level,
      coalesce((p_fields->>'is_active')::boolean, true),
      nullif(p_fields->>'expires_at', '')::timestamptz,
      v_note
    ) returning * into v_row;
  else
    update public.test_assignments set
      assigned_to_user_uid = coalesce(v_assigned_to_user_uid, assigned_to_user_uid),
      target_exam = coalesce(v_target_exam, target_exam),
      target_syllabus = coalesce(v_target_syllabus, target_syllabus),
      target_class_level = coalesce(v_target_class_level, target_class_level),
      is_active = coalesce((p_fields->>'is_active')::boolean, is_active),
      expires_at = coalesce(nullif(p_fields->>'expires_at', '')::timestamptz, expires_at),
      note = coalesce(v_note, note),
      updated_at = now()
    where id = p_id
    returning * into v_row;

    if not found then
      raise exception 'assignment % not found', p_id;
    end if;
  end if;

  return v_row;
end;
$function$;

-- ── admin_upsert(text,text,text,text,text,text) ─────────────────
CREATE OR REPLACE FUNCTION public.admin_upsert(p_caller text, p_uid text, p_email text, p_name text, p_role text, p_passcode text)
 RETURNS json
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE v_role TEXT;
BEGIN
  perform assert_verified_admin(p_caller);  -- P0.5
  SELECT role INTO v_role FROM admins WHERE uid = p_caller AND is_active = true;
  IF v_role IS DISTINCT FROM 'superadmin' THEN
    RETURN json_build_object('error', 'Unauthorized');
  END IF;
  IF length(p_passcode) <> 6 OR p_passcode !~ '^\d{6}$' THEN
    RETURN json_build_object('error', 'Passcode must be exactly 6 digits');
  END IF;
  INSERT INTO admins (uid, email, name, role, passcode_hash, added_by)
  VALUES (p_uid, p_email, p_name, p_role,
          encode(sha256(p_passcode::bytea), 'hex'), p_caller)
  ON CONFLICT (uid) DO UPDATE SET
    email         = EXCLUDED.email,
    name          = EXCLUDED.name,
    role          = EXCLUDED.role,
    passcode_hash = EXCLUDED.passcode_hash,
    updated_at    = NOW();
  RETURN json_build_object('ok', true);
END;
$function$;

-- ── coaching_admin_delete(text,text) ────────────────────────────
CREATE OR REPLACE FUNCTION public.coaching_admin_delete(p_caller text, p_target_uid text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
  caller_role TEXT;
BEGIN
  perform assert_verified_admin(p_caller);  -- P0.5
  SELECT role INTO caller_role FROM admins WHERE uid = p_caller AND is_active = true LIMIT 1;
  IF caller_role IS NULL OR caller_role NOT IN ('superadmin','admin') THEN
    RAISE EXCEPTION 'Access denied';
  END IF;
  DELETE FROM coaching_admins WHERE uid = p_target_uid;
END;
$function$;

-- ── coaching_admin_upsert(text,text,text,text,uuid,text) ────────
CREATE OR REPLACE FUNCTION public.coaching_admin_upsert(p_caller text, p_uid text, p_email text, p_name text, p_centre_id uuid, p_role text DEFAULT 'instructor'::text)
 RETURNS json
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
  caller_role TEXT;
  result      JSON;
BEGIN
  perform assert_verified_admin(p_caller);  -- P0.5
  SELECT role INTO caller_role FROM admins WHERE uid = p_caller AND is_active = true LIMIT 1;
  IF caller_role IS NULL OR caller_role NOT IN ('superadmin','admin') THEN
    RAISE EXCEPTION 'Only platform admins can add coaching admins';
  END IF;

  INSERT INTO coaching_admins (uid, email, name, centre_id, role, added_by)
  VALUES (p_uid, p_email, p_name, p_centre_id, p_role, p_caller)
  ON CONFLICT (uid) DO UPDATE
    SET email     = EXCLUDED.email,
        name      = EXCLUDED.name,
        centre_id = EXCLUDED.centre_id,
        role      = EXCLUDED.role;

  SELECT row_to_json(r) INTO result
  FROM (SELECT * FROM coaching_admins WHERE uid = p_uid LIMIT 1) r;

  RETURN result;
END;
$function$;

commit;
