-- P0.5 batch: pii — bind admin RPCs to a verified identity.
--
-- GENERATED by scripts/gen-p05-guards.mjs. Each function below is re-emitted
-- exactly as pg_get_functiondef() returned it, with a single line added after
-- the outer BEGIN:
--
--     perform assert_verified_admin(p_caller);  -- P0.5
--
-- Nothing else in any body changes. The pre-existing inline admins lookup is
-- left in place on purpose, so the diff is one statement per function.
--
-- assert_verified_admin() requires verified_uid() to be non-null, to equal
-- p_caller, and to be an active admin. That blocks anon-key callers (the live
-- bypass) and also blocks a signed-in non-admin passing a known admin UID,
-- which a grant-based gate could never do — and, unlike the P0 role gate, it
-- does not depend on the request arriving as `authenticated`. Every request in
-- this project arrives as `anon`; only auth.jwt() is populated.
--
-- Functions in this batch: 5
--   admin_get_user(text,text)
--   admin_list_all_firebase_uids(text)
--   admin_list_doubt_chats(text,integer)
--   admin_list_doubt_messages(text,uuid[])
--   admin_search_users(text,text,integer)

begin;


-- ── admin_get_user(text,text) ───────────────────────────────────
CREATE OR REPLACE FUNCTION public.admin_get_user(p_caller text, p_uid text)
 RETURNS users
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare v_role text; v_row public.users;
begin
  perform assert_verified_admin(p_caller);  -- P0.5
  select role into v_role from admins where uid = p_caller and is_active = true;
  if v_role is null or v_role not in ('superadmin','admin') then raise exception 'Access denied'; end if;
  select * into v_row from public.users where firebase_uid = p_uid;
  return v_row;
end; $function$;

-- ── admin_list_all_firebase_uids(text) ──────────────────────────
CREATE OR REPLACE FUNCTION public.admin_list_all_firebase_uids(p_caller text)
 RETURNS SETOF text
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare v_role text;
begin
  perform assert_verified_admin(p_caller);  -- P0.5
  select role into v_role from admins where uid = p_caller and is_active = true;
  if v_role is null or v_role not in ('superadmin','admin') then raise exception 'Access denied'; end if;
  return query select firebase_uid from public.users limit 2000;
end; $function$;

-- ── admin_list_doubt_chats(text,integer) ────────────────────────
CREATE OR REPLACE FUNCTION public.admin_list_doubt_chats(p_caller text, p_limit integer DEFAULT 100)
 RETURNS SETOF doubt_chats
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare v_role text;
begin
  perform assert_verified_admin(p_caller);  -- P0.5
  select role into v_role from admins where uid = p_caller and is_active = true;
  if v_role is null or v_role not in ('superadmin','admin') then raise exception 'Access denied'; end if;
  return query select * from doubt_chats order by created_at desc limit p_limit;
end;
$function$;

-- ── admin_list_doubt_messages(text,uuid[]) ──────────────────────
CREATE OR REPLACE FUNCTION public.admin_list_doubt_messages(p_caller text, p_chat_ids uuid[])
 RETURNS SETOF doubt_messages
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare v_role text;
begin
  perform assert_verified_admin(p_caller);  -- P0.5
  select role into v_role from admins where uid = p_caller and is_active = true;
  if v_role is null or v_role not in ('superadmin','admin') then raise exception 'Access denied'; end if;
  return query select * from doubt_messages where chat_id = any(p_chat_ids) order by created_at asc;
end;
$function$;

-- ── admin_search_users(text,text,integer) ───────────────────────
CREATE OR REPLACE FUNCTION public.admin_search_users(p_caller text, p_query text, p_limit integer DEFAULT 8)
 RETURNS SETOF users
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare v_role text;
begin
  perform assert_verified_admin(p_caller);  -- P0.5
  select role into v_role from admins where uid = p_caller and is_active = true;
  if v_role is null or v_role not in ('superadmin','admin') then raise exception 'Access denied'; end if;
  return query
    select * from public.users
    where firebase_uid = p_query
       or email ilike '%' || p_query || '%'
       or display_name ilike '%' || p_query || '%'
    limit p_limit;
end; $function$;

commit;
