-- P0.5 batch: lists — bind admin RPCs to a verified identity.
--
-- GENERATED by scripts/gen-p05-guards.mjs. Each function below is re-emitted
-- exactly as pg_get_functiondef() returned it, with a single line added after
-- the outer BEGIN:
--
--     perform assert_verified_admin(p_caller);  -- P0.5
--
-- Nothing else in any body changes. The pre-existing inline admins lookup is
-- left in place on purpose, so the diff is one statement per function.
--
-- assert_verified_admin() requires verified_uid() to be non-null, to equal
-- p_caller, and to be an active admin. That blocks anon-key callers (the live
-- bypass) and also blocks a signed-in non-admin passing a known admin UID,
-- which a grant-based gate could never do — and, unlike the P0 role gate, it
-- does not depend on the request arriving as `authenticated`. Every request in
-- this project arrives as `anon`; only auth.jwt() is populated.
--
-- Functions in this batch: 23
--   admin_get_activity_log(text,integer,integer)
--   admin_get_coaching_centre_count(text)
--   admin_get_feature_flags(text)
--   admin_get_notification_history(text,integer)
--   admin_get_platform_settings(text)
--   admin_get_published_test(text,uuid)
--   admin_get_top_misconceptions(text,integer,integer)
--   admin_list_active_centres_lite(text)
--   admin_list_centre_assignments(text,uuid)
--   admin_list_centre_students(text,uuid)
--   admin_list_coaching_centres(text)
--   admin_list_email_templates(text)
--   admin_list_exam_categories(text)
--   admin_list_onboarding_options(text)
--   admin_list_published_tests(text)
--   admin_list_quota_overrides(text)
--   admin_list_referrals(text)
--   admin_list_study_notes(text)
--   admin_list_subscriptions(text)
--   admin_list_test_assignments(text,uuid)
--   admin_list(text)
--   admin_search_published_tests(text,text,integer)
--   coaching_admin_list(text)

begin;


-- ── admin_get_activity_log(text,integer,integer) ────────────────
CREATE OR REPLACE FUNCTION public.admin_get_activity_log(p_caller text, p_limit integer DEFAULT 100, p_offset integer DEFAULT 0)
 RETURNS TABLE(id uuid, entity_type text, entity_id text, action text, actor_uid text, actor_role text, actor_name text, actor_email text, diff jsonb, note text, created_at timestamp with time zone)
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN

  perform assert_verified_admin(p_caller);  -- P0.5
  IF NOT EXISTS (
    SELECT 1 FROM admins WHERE uid = p_caller AND is_active = true
  ) THEN
    RAISE EXCEPTION 'unauthorized';
  END IF;

  RETURN QUERY
    SELECT c.id, c.entity_type, c.entity_id, c.action,
           c.actor_uid, c.actor_role,
           a.name  AS actor_name,
           a.email AS actor_email,
           c.diff, c.note, c.created_at
      FROM changelog c
      LEFT JOIN admins a ON a.uid = c.actor_uid
     ORDER BY c.created_at DESC
     LIMIT p_limit
    OFFSET p_offset;
END;
$function$;

-- ── admin_get_coaching_centre_count(text) ───────────────────────
CREATE OR REPLACE FUNCTION public.admin_get_coaching_centre_count(p_caller text)
 RETURNS bigint
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare v_role text; v_count bigint;
begin
  perform assert_verified_admin(p_caller);  -- P0.5
  select role into v_role from admins where uid = p_caller and is_active = true;
  if v_role is null or v_role not in ('superadmin','admin') then raise exception 'Access denied'; end if;
  select count(*) into v_count from coaching_centres;
  return v_count;
end; $function$;

-- ── admin_get_feature_flags(text) ───────────────────────────────
CREATE OR REPLACE FUNCTION public.admin_get_feature_flags(p_caller text)
 RETURNS TABLE(key text, enabled boolean)
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN

  perform assert_verified_admin(p_caller);  -- P0.5
  IF NOT EXISTS (
    SELECT 1 FROM admins WHERE uid = p_caller AND is_active = true
  ) THEN
    RAISE EXCEPTION 'unauthorized';
  END IF;

  RETURN QUERY
    SELECT ff.key, ff.enabled
      FROM feature_flags ff
     ORDER BY ff.key;
END;
$function$;

-- ── admin_get_notification_history(text,integer) ────────────────
CREATE OR REPLACE FUNCTION public.admin_get_notification_history(p_caller text, p_limit integer DEFAULT 30)
 RETURNS TABLE(id uuid, user_id text, title text, body text, type text, url text, is_read boolean, created_at timestamp with time zone, expires_at timestamp with time zone)
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN

  perform assert_verified_admin(p_caller);  -- P0.5
  IF NOT EXISTS (
    SELECT 1 FROM admins WHERE uid = p_caller AND is_active = true
  ) THEN
    RAISE EXCEPTION 'unauthorized';
  END IF;

  RETURN QUERY
    SELECT n.id, n.user_id, n.title, n.body, n.type, n.url, n.is_read, n.created_at, n.expires_at
      FROM in_app_notifications n
     ORDER BY n.created_at DESC
     LIMIT p_limit;
END;
$function$;

-- ── admin_get_platform_settings(text) ───────────────────────────
CREATE OR REPLACE FUNCTION public.admin_get_platform_settings(p_caller text)
 RETURNS json
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE v_role TEXT;
BEGIN
  perform assert_verified_admin(p_caller);  -- P0.5
  SELECT role INTO v_role FROM admins WHERE uid = p_caller AND is_active = true;
  IF v_role IS NULL OR v_role NOT IN ('superadmin','admin') THEN RAISE EXCEPTION 'Access denied'; END IF;
  RETURN (SELECT json_object_agg(key, value) FROM platform_settings);
END;
$function$;

-- ── admin_get_published_test(text,uuid) ─────────────────────────
CREATE OR REPLACE FUNCTION public.admin_get_published_test(p_caller text, p_id uuid)
 RETURNS published_tests
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_row public.published_tests;
begin
  perform assert_verified_admin(p_caller);  -- P0.5
  if not public.is_active_admin(p_caller) then
    raise exception 'Access denied';
  end if;
  select * into v_row from public.published_tests where id = p_id;
  return v_row;
end;
$function$;

-- ── admin_get_top_misconceptions(text,integer,integer) ──────────
CREATE OR REPLACE FUNCTION public.admin_get_top_misconceptions(p_caller text, p_days integer DEFAULT 7, p_limit integer DEFAULT 20)
 RETURNS TABLE(subject text, chapter text, distractor text, correct_answer text, question_text text, total_occurrences bigint, distinct_students bigint, last_seen_at timestamp with time zone)
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare v_role text;
begin
  perform assert_verified_admin(p_caller);  -- P0.5
  select role into v_role from admins where uid = p_caller and is_active = true;
  if v_role is null or v_role not in ('superadmin','admin') then
    raise exception 'Access denied';
  end if;

  return query
  select
    m.subject, m.chapter, m.distractor, m.correct_answer, m.question_text,
    sum(m.count)                as total_occurrences,
    count(distinct m.user_id)   as distinct_students,
    max(m.last_seen_at)         as last_seen_at
  from public.concept_misconceptions m
  where m.last_seen_at >= now() - (p_days || ' days')::interval
  group by m.subject, m.chapter, m.distractor, m.correct_answer, m.question_text
  order by total_occurrences desc, last_seen_at desc
  limit p_limit;
end;
$function$;

-- ── admin_list_active_centres_lite(text) ────────────────────────
CREATE OR REPLACE FUNCTION public.admin_list_active_centres_lite(p_caller text)
 RETURNS TABLE(id uuid, name text, city text)
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare v_role text;
begin
  perform assert_verified_admin(p_caller);  -- P0.5
  select role into v_role from admins where uid = p_caller and is_active = true;
  if v_role is null or v_role not in ('superadmin','admin') then raise exception 'Access denied'; end if;
  return query select c.id, c.name, c.city from coaching_centres c where c.status = 'active';
end; $function$;

-- ── admin_list_centre_assignments(text,uuid) ────────────────────
CREATE OR REPLACE FUNCTION public.admin_list_centre_assignments(p_caller text, p_centre_id uuid)
 RETURNS SETOF coaching_assignments
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare v_role text;
begin
  perform assert_verified_admin(p_caller);  -- P0.5
  select role into v_role from admins where uid = p_caller and is_active = true;
  if v_role is null or v_role not in ('superadmin','admin') then raise exception 'Access denied'; end if;
  return query select * from coaching_assignments where centre_id = p_centre_id order by created_at desc;
end; $function$;

-- ── admin_list_centre_students(text,uuid) ───────────────────────
CREATE OR REPLACE FUNCTION public.admin_list_centre_students(p_caller text, p_centre_id uuid)
 RETURNS SETOF coaching_students
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare v_role text;
begin
  perform assert_verified_admin(p_caller);  -- P0.5
  select role into v_role from admins where uid = p_caller and is_active = true;
  if v_role is null or v_role not in ('superadmin','admin') then raise exception 'Access denied'; end if;
  return query select * from coaching_students where centre_id = p_centre_id order by created_at desc;
end; $function$;

-- ── admin_list_coaching_centres(text) ───────────────────────────
CREATE OR REPLACE FUNCTION public.admin_list_coaching_centres(p_caller text)
 RETURNS SETOF coaching_centres
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare v_role text;
begin
  perform assert_verified_admin(p_caller);  -- P0.5
  select role into v_role from admins where uid = p_caller and is_active = true;
  if v_role is null or v_role not in ('superadmin','admin') then raise exception 'Access denied'; end if;
  return query select * from coaching_centres order by created_at desc;
end; $function$;

-- ── admin_list_email_templates(text) ────────────────────────────
CREATE OR REPLACE FUNCTION public.admin_list_email_templates(p_caller text)
 RETURNS SETOF email_templates
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN

  perform assert_verified_admin(p_caller);  -- P0.5
  IF NOT EXISTS (SELECT 1 FROM admins WHERE uid = p_caller AND is_active = true) THEN
    RAISE EXCEPTION 'Unauthorized';
  END IF;
  RETURN QUERY SELECT * FROM email_templates ORDER BY template_key;
END;
$function$;

-- ── admin_list_exam_categories(text) ────────────────────────────
CREATE OR REPLACE FUNCTION public.admin_list_exam_categories(p_caller text)
 RETURNS SETOF exam_categories
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN

  perform assert_verified_admin(p_caller);  -- P0.5
  IF NOT EXISTS(SELECT 1 FROM admins WHERE uid = p_caller AND is_active = true) THEN
    RAISE EXCEPTION 'Not authorized';
  END IF;
  RETURN QUERY SELECT * FROM exam_categories WHERE is_active = true ORDER BY category_kind, sort_order, label;
END;
$function$;

-- ── admin_list_onboarding_options(text) ─────────────────────────
CREATE OR REPLACE FUNCTION public.admin_list_onboarding_options(p_caller text)
 RETURNS SETOF onboarding_category_display
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare v_role text;
begin
  perform assert_verified_admin(p_caller);  -- P0.5
  select role into v_role from admins where uid = p_caller and is_active = true;
  if v_role is null or v_role not in ('superadmin','admin') then raise exception 'Access denied'; end if;
  return query select * from onboarding_category_display order by option_type, sort_order;
end;
$function$;

-- ── admin_list_published_tests(text) ────────────────────────────
CREATE OR REPLACE FUNCTION public.admin_list_published_tests(p_caller text)
 RETURNS SETOF published_tests
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin

  perform assert_verified_admin(p_caller);  -- P0.5
  if not public.is_active_admin(p_caller) then
    raise exception 'Access denied';
  end if;
  return query select * from public.published_tests order by created_at desc;
end;
$function$;

-- ── admin_list_quota_overrides(text) ────────────────────────────
CREATE OR REPLACE FUNCTION public.admin_list_quota_overrides(p_caller text)
 RETURNS TABLE(id uuid, user_id text, ai_questions integer, veda_messages integer, mock_tests integer, paper_evaluations integer, podcasts integer, paper_generations integer, reason text, expires_at timestamp with time zone, created_at timestamp with time zone, updated_at timestamp with time zone)
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN

  perform assert_verified_admin(p_caller);  -- P0.5
  IF NOT EXISTS (SELECT 1 FROM admins WHERE uid = p_caller AND is_active = true) THEN
    RAISE EXCEPTION 'Unauthorized';
  END IF;
  RETURN QUERY
    SELECT o.id, o.user_id, o.ai_questions, o.veda_messages, o.mock_tests,
           o.paper_evaluations, o.podcasts, o.paper_generations,
           o.reason, o.expires_at, o.created_at, o.updated_at
    FROM   quota_overrides o
    ORDER  BY o.created_at DESC;
END;
$function$;

-- ── admin_list_referrals(text) ──────────────────────────────────
CREATE OR REPLACE FUNCTION public.admin_list_referrals(p_caller text)
 RETURNS TABLE(referrer_uid text, referrer_name text, referrer_email text, code text, conversions integer, credits_earned integer, pending integer, referred_uid text, referred_name text, referred_email text, converted boolean, days_granted integer, redeemed_at timestamp with time zone, converted_at timestamp with time zone)
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE v_role TEXT;
BEGIN
  perform assert_verified_admin(p_caller);  -- P0.5
  SELECT a.role INTO v_role FROM admins a WHERE a.uid = p_caller AND a.is_active = true;
  IF v_role IS NULL OR v_role NOT IN ('superadmin','admin') THEN
    RAISE EXCEPTION 'Access denied';
  END IF;

  -- LEFT JOIN from referral_codes, so a student who has generated a code but
  -- never had it used still appears (with a null referred_uid). Without that
  -- the screen silently hides everyone who has shared but not yet landed
  -- anyone — which early on is most of them.
  RETURN QUERY
  SELECT
    rc.user_id,
    ru_referrer.display_name,
    ru_referrer.email,
    rc.code,
    rc.uses,
    rc.credits_earned,
    (SELECT count(*)::int FROM referral_uses x
      WHERE x.referrer_uid = rc.user_id AND NOT x.converted),
    u.referred_uid,
    ru_referred.display_name,
    ru_referred.email,
    u.converted,
    u.days_granted,
    u.created_at,
    u.converted_at
  FROM referral_codes rc
  LEFT JOIN referral_uses u        ON u.referrer_uid = rc.user_id
  LEFT JOIN users ru_referrer      ON ru_referrer.firebase_uid = rc.user_id
  LEFT JOIN users ru_referred      ON ru_referred.firebase_uid = u.referred_uid
  ORDER BY u.created_at DESC NULLS LAST, rc.created_at DESC;
END;
$function$;

-- ── admin_list_study_notes(text) ────────────────────────────────
CREATE OR REPLACE FUNCTION public.admin_list_study_notes(p_caller text)
 RETURNS json
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE v_role TEXT;
BEGIN
  perform assert_verified_admin(p_caller);  -- P0.5
  SELECT role INTO v_role FROM admins WHERE uid = p_caller AND is_active = true;
  IF v_role IS NULL OR v_role NOT IN ('superadmin','admin') THEN RAISE EXCEPTION 'Access denied'; END IF;
  RETURN (SELECT json_agg(n ORDER BY n.created_at DESC) FROM study_notes n);
END;
$function$;

-- ── admin_list_subscriptions(text) ──────────────────────────────
CREATE OR REPLACE FUNCTION public.admin_list_subscriptions(p_caller text)
 RETURNS json
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare v_role text;
begin
  perform assert_verified_admin(p_caller);  -- P0.5
  select role into v_role from admins where uid = p_caller and is_active = true;
  if v_role is null or v_role not in ('superadmin','admin') then
    raise exception 'Access denied';
  end if;

  return (
    select coalesce(json_agg(x order by x.updated_at desc), '[]'::json)
    from (
      select s.user_id, s.plan, s.status, s.starts_at, s.expires_at,
             s.amount_paid, s.created_at, s.updated_at
      from subscriptions s
    ) x
  );
end;
$function$;

-- ── admin_list_test_assignments(text,uuid) ──────────────────────
CREATE OR REPLACE FUNCTION public.admin_list_test_assignments(p_caller text, p_test_id uuid DEFAULT NULL::uuid)
 RETURNS SETOF test_assignments
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin

  perform assert_verified_admin(p_caller);  -- P0.5
  if not public.is_active_admin(p_caller) then
    raise exception 'Access denied';
  end if;
  if p_test_id is null then
    return query select * from public.test_assignments order by created_at desc;
  end if;
  return query select * from public.test_assignments where test_id = p_test_id order by created_at desc;
end;
$function$;

-- ── admin_list(text) ────────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.admin_list(p_caller text)
 RETURNS json
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE v_role TEXT;
BEGIN
  perform assert_verified_admin(p_caller);  -- P0.5
  SELECT role INTO v_role FROM admins WHERE uid = p_caller AND is_active = true;
  IF v_role IS DISTINCT FROM 'superadmin' THEN
    RETURN json_build_object('error', 'Unauthorized');
  END IF;
  RETURN (
    SELECT json_agg(row_to_json(a))
    FROM (SELECT uid, email, name, role, is_active, added_by, created_at, updated_at
          FROM admins ORDER BY created_at) a
  );
END;
$function$;

-- ── admin_search_published_tests(text,text,integer) ─────────────
CREATE OR REPLACE FUNCTION public.admin_search_published_tests(p_caller text, p_query text, p_limit integer DEFAULT 5)
 RETURNS SETOF published_tests
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_term text := '%' || coalesce(p_query, '') || '%';
begin
  perform assert_verified_admin(p_caller);  -- P0.5
  if not public.is_active_admin(p_caller) then
    raise exception 'Access denied';
  end if;
  return query
    select * from public.published_tests
    where title ilike v_term
       or subject ilike v_term
       or exam_type ilike v_term
    order by created_at desc
    limit p_limit;
end;
$function$;

-- ── coaching_admin_list(text) ───────────────────────────────────
CREATE OR REPLACE FUNCTION public.coaching_admin_list(p_caller text)
 RETURNS json
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
  caller_role TEXT;
  caller_centre UUID;
  result JSON;
BEGIN
  perform assert_verified_admin(p_caller);  -- P0.5
  -- Check if caller is superadmin
  SELECT role INTO caller_role FROM admins WHERE uid = p_caller LIMIT 1;

  IF caller_role IN ('superadmin','admin') THEN
    SELECT json_agg(r) INTO result
    FROM (
      SELECT ca.*, cc.name AS centre_name
      FROM coaching_admins ca
      JOIN coaching_centres cc ON cc.id = ca.centre_id
      ORDER BY ca.created_at DESC
    ) r;
  ELSE
    -- Check if caller is centre_admin
    SELECT centre_id INTO caller_centre
    FROM coaching_admins WHERE uid = p_caller AND role = 'centre_admin' AND is_active = true LIMIT 1;

    IF caller_centre IS NULL THEN
      RAISE EXCEPTION 'Access denied';
    END IF;

    SELECT json_agg(r) INTO result
    FROM (
      SELECT ca.*, cc.name AS centre_name
      FROM coaching_admins ca
      JOIN coaching_centres cc ON cc.id = ca.centre_id
      WHERE ca.centre_id = caller_centre
      ORDER BY ca.created_at DESC
    ) r;
  END IF;

  RETURN COALESCE(result, '[]'::json);
END;
$function$;

commit;
