-- P0.5 batch: mutations — bind admin RPCs to a verified identity.
--
-- GENERATED by scripts/gen-p05-guards.mjs. Each function below is re-emitted
-- exactly as pg_get_functiondef() returned it, with a single line added after
-- the outer BEGIN:
--
--     perform assert_verified_admin(p_caller);  -- P0.5
--
-- Nothing else in any body changes. The pre-existing inline admins lookup is
-- left in place on purpose, so the diff is one statement per function.
--
-- assert_verified_admin() requires verified_uid() to be non-null, to equal
-- p_caller, and to be an active admin. That blocks anon-key callers (the live
-- bypass) and also blocks a signed-in non-admin passing a known admin UID,
-- which a grant-based gate could never do — and, unlike the P0 role gate, it
-- does not depend on the request arriving as `authenticated`. Every request in
-- this project arrives as `anon`; only auth.jwt() is populated.
--
-- Functions in this batch: 12
--   admin_bulk_set_study_notes_published(text,uuid[],boolean)
--   admin_cancel_subscription(text,text)
--   admin_change_passcode(text,text,text)
--   admin_delete_exam_category(text,uuid)
--   admin_delete_syllabus_node(text,uuid)
--   admin_reset_email_template(text,text)
--   admin_reset_weekly_field(text,text,text,text,text)
--   admin_toggle_active(text,text,boolean)
--   admin_toggle_study_note_publish(text,uuid,boolean)
--   admin_update_user(text,text,jsonb)
--   admin_upsert_email_template(text,text,text,text,text,text,text,text[],text,text,text)
--   coaching_admin_toggle_active(text,text,boolean)

begin;


-- ── admin_bulk_set_study_notes_published(text,uuid[],boolean) ───
CREATE OR REPLACE FUNCTION public.admin_bulk_set_study_notes_published(p_caller text, p_ids uuid[], p_published boolean)
 RETURNS json
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare v_role text; v_count int;
begin
  perform assert_verified_admin(p_caller);  -- P0.5
  select role into v_role from admins where uid = p_caller and is_active = true;
  if v_role is null or v_role not in ('superadmin','admin') then raise exception 'Access denied'; end if;

  update study_notes set is_published = p_published, updated_at = now()
  where id = any(p_ids);
  get diagnostics v_count = row_count;

  return json_build_object('ok', true, 'updated', v_count);
end;
$function$;

-- ── admin_cancel_subscription(text,text) ────────────────────────
CREATE OR REPLACE FUNCTION public.admin_cancel_subscription(p_caller text, p_user_id text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN

  perform assert_verified_admin(p_caller);  -- P0.5
  IF NOT EXISTS (SELECT 1 FROM admins WHERE uid = p_caller AND is_active = true) THEN
    RAISE EXCEPTION 'Not authorized';
  END IF;

  UPDATE subscriptions
  SET status = 'cancelled', updated_at = now()
  WHERE user_id = p_user_id;
END;
$function$;

-- ── admin_change_passcode(text,text,text) ───────────────────────
CREATE OR REPLACE FUNCTION public.admin_change_passcode(p_caller text, p_target_uid text, p_passcode text)
 RETURNS json
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE v_role TEXT;
BEGIN
  perform assert_verified_admin(p_caller);  -- P0.5
  SELECT role INTO v_role FROM admins WHERE uid = p_caller AND is_active = true;
  IF v_role IS DISTINCT FROM 'superadmin' THEN
    RETURN json_build_object('error', 'Unauthorized');
  END IF;
  IF length(p_passcode) <> 6 OR p_passcode !~ '^\d{6}$' THEN
    RETURN json_build_object('error', 'Passcode must be 6 digits');
  END IF;
  UPDATE admins
     SET passcode_hash = encode(sha256(p_passcode::bytea), 'hex'),
         updated_at    = NOW()
   WHERE uid = p_target_uid;
  RETURN json_build_object('ok', true);
END;
$function$;

-- ── admin_delete_exam_category(text,uuid) ───────────────────────
CREATE OR REPLACE FUNCTION public.admin_delete_exam_category(p_caller text, p_id uuid)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN

  perform assert_verified_admin(p_caller);  -- P0.5
  IF NOT EXISTS(SELECT 1 FROM admins WHERE uid = p_caller AND is_active = true) THEN
    RAISE EXCEPTION 'Not authorized';
  END IF;
  UPDATE exam_categories SET is_active = false, updated_at = now() WHERE id = p_id;
END;
$function$;

-- ── admin_delete_syllabus_node(text,uuid) ───────────────────────
CREATE OR REPLACE FUNCTION public.admin_delete_syllabus_node(p_caller text, p_id uuid)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN

  perform assert_verified_admin(p_caller);  -- P0.5
  IF NOT EXISTS (SELECT 1 FROM admins WHERE uid = p_caller AND is_active = true) THEN
    RAISE EXCEPTION 'unauthorized';
  END IF;
  UPDATE syllabus_nodes SET is_active = false WHERE id = p_id;
END;
$function$;

-- ── admin_reset_email_template(text,text) ───────────────────────
CREATE OR REPLACE FUNCTION public.admin_reset_email_template(p_caller text, p_template_key text)
 RETURNS email_templates
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_row email_templates;
BEGIN
  perform assert_verified_admin(p_caller);  -- P0.5
  IF NOT EXISTS (SELECT 1 FROM admins WHERE uid = p_caller AND is_active = true) THEN
    RAISE EXCEPTION 'Unauthorized';
  END IF;

  UPDATE email_templates SET
    label = d.label, description = d.description, subject = d.subject, heading = d.heading,
    body_text = d.body_text, bullet_points = d.bullet_points, button_label = d.button_label,
    button_path = d.button_path, footer_note = d.footer_note,
    updated_at = now(), updated_by = p_caller
  FROM (VALUES
    ('welcome', 'Welcome Email', 'Sent once, right after a student completes onboarding.',
     'Welcome to EaseWithExam, {{name}}! 🎉', 'Hey {{name}}, you''re all set 👋',
     'Your account is ready and set up for {{exam}}. Here''s what''s unlocked on your free plan right now:',
     ARRAY['20 AI practice questions every day','2 full question papers per day','2 full mock tests per week','EWE — your AI study tutor (15 messages/day)','Daily challenge + basic analytics'],
     'Start Practicing', '/practice/generate', 'Good luck with {{exam}} — we''re rooting for you.'),
    ('paper_ready', 'Paper Ready Email', 'Sent when a background-generated paper finishes.',
     'Your paper is ready 📝', 'Your paper is ready!',
     '{{examType}} · {{subject}} — {{count}} questions, generated and waiting for you in Exam Center.',
     '{}', 'Start the Paper', '/exams?tab=papers', ''),
    ('subscription_active', 'Subscription Activated Email', 'Sent right after a Razorpay payment is verified and a paid plan activates.',
     '{{planName}} is active — welcome aboard! 🎉', '{{planName}} activated',
     'Thanks for upgrading. Every AI limit is lifted — unlimited practice questions, unlimited EWE tutoring, the Misconception Engine, and full mock-test access are unlocked on your account right now.',
     '{}', 'Go to Dashboard', '/dashboard', ''),
    ('verify_email', 'Connect-Email Verification Code', 'Sent when a phone-signup student adds an email for notifications (Notifications settings → Connect email).',
     'Your EaseWithExam verification code', 'Confirm your email',
     'Enter this code in EaseWithExam to start receiving email notifications at this address.',
     '{}', '', '', 'This code expires in 30 minutes. Didn''t request this? You can ignore this email.')
  ) AS d(template_key, label, description, subject, heading, body_text, bullet_points, button_label, button_path, footer_note)
  WHERE email_templates.template_key = d.template_key AND d.template_key = p_template_key
  RETURNING * INTO v_row;

  IF v_row.id IS NULL THEN
    RAISE EXCEPTION 'Unknown template_key: %', p_template_key;
  END IF;

  RETURN v_row;
END;
$function$;

-- ── admin_reset_weekly_field(text,text,text,text,text) ──────────
CREATE OR REPLACE FUNCTION public.admin_reset_weekly_field(p_caller text, p_user_id text, p_field text, p_week_start text, p_week_end text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  _allowed text[] := ARRAY['mock_tests_used'];
BEGIN
  perform assert_verified_admin(p_caller);  -- P0.5
  IF NOT EXISTS (SELECT 1 FROM admins WHERE uid = p_caller AND is_active = true) THEN
    RAISE EXCEPTION 'Unauthorized';
  END IF;
  IF p_field != ALL(_allowed) THEN
    RAISE EXCEPTION 'invalid weekly quota field: %', p_field;
  END IF;

  EXECUTE format(
    'UPDATE daily_usage_quota SET %I = 0 WHERE user_id = $1 AND usage_date BETWEEN $2::date AND $3::date',
    p_field
  ) USING p_user_id, p_week_start, p_week_end;
END;
$function$;

-- ── admin_toggle_active(text,text,boolean) ──────────────────────
CREATE OR REPLACE FUNCTION public.admin_toggle_active(p_caller text, p_target_uid text, p_active boolean)
 RETURNS json
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE v_role TEXT;
BEGIN
  perform assert_verified_admin(p_caller);  -- P0.5
  SELECT role INTO v_role FROM admins WHERE uid = p_caller AND is_active = true;
  IF v_role IS DISTINCT FROM 'superadmin' THEN
    RETURN json_build_object('error', 'Unauthorized');
  END IF;
  IF p_caller = p_target_uid THEN
    RETURN json_build_object('error', 'Cannot disable your own account');
  END IF;
  UPDATE admins SET is_active = p_active, updated_at = NOW() WHERE uid = p_target_uid;
  RETURN json_build_object('ok', true);
END;
$function$;

-- ── admin_toggle_study_note_publish(text,uuid,boolean) ──────────
CREATE OR REPLACE FUNCTION public.admin_toggle_study_note_publish(p_caller text, p_id uuid, p_published boolean)
 RETURNS json
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE v_role TEXT;
BEGIN
  perform assert_verified_admin(p_caller);  -- P0.5
  SELECT role INTO v_role FROM admins WHERE uid = p_caller AND is_active = true;
  IF v_role IS NULL OR v_role NOT IN ('superadmin','admin') THEN RAISE EXCEPTION 'Access denied'; END IF;
  UPDATE study_notes SET is_published = p_published, updated_at = NOW() WHERE id = p_id;
  RETURN json_build_object('ok', true);
END;
$function$;

-- ── admin_update_user(text,text,jsonb) ──────────────────────────
CREATE OR REPLACE FUNCTION public.admin_update_user(p_caller text, p_target_uid text, p_fields jsonb)
 RETURNS users
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare v_role text; v_row public.users;
begin
  perform assert_verified_admin(p_caller);  -- P0.5
  select role into v_role from admins where uid = p_caller and is_active = true;
  if v_role is null or v_role not in ('superadmin','admin') then raise exception 'Access denied'; end if;
  update public.users set
    display_name = coalesce(p_fields->>'display_name', display_name),
    target_exam  = coalesce(p_fields->>'target_exam', target_exam),
    syllabus     = coalesce(p_fields->>'syllabus', syllabus),
    class_level  = coalesce(p_fields->>'class_level', class_level)
  where firebase_uid = p_target_uid
  returning * into v_row;
  return v_row;
end; $function$;

-- ── admin_upsert_email_template(text,text,text,text,text,text,text,text[],text,text,text) 
CREATE OR REPLACE FUNCTION public.admin_upsert_email_template(p_caller text, p_template_key text, p_label text, p_description text, p_subject text, p_heading text, p_body_text text, p_bullet_points text[], p_button_label text, p_button_path text, p_footer_note text)
 RETURNS email_templates
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_row email_templates;
BEGIN
  perform assert_verified_admin(p_caller);  -- P0.5
  IF NOT EXISTS (SELECT 1 FROM admins WHERE uid = p_caller AND is_active = true) THEN
    RAISE EXCEPTION 'Unauthorized';
  END IF;

  UPDATE email_templates SET
    label = p_label, description = p_description, subject = p_subject, heading = p_heading,
    body_text = p_body_text, bullet_points = p_bullet_points, button_label = p_button_label,
    button_path = p_button_path, footer_note = p_footer_note,
    updated_at = now(), updated_by = p_caller
  WHERE template_key = p_template_key
  RETURNING * INTO v_row;

  IF v_row.id IS NULL THEN
    RAISE EXCEPTION 'Unknown template_key: %', p_template_key;
  END IF;

  RETURN v_row;
END;
$function$;

-- ── coaching_admin_toggle_active(text,text,boolean) ─────────────
CREATE OR REPLACE FUNCTION public.coaching_admin_toggle_active(p_caller text, p_target_uid text, p_active boolean)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
  caller_role TEXT;
BEGIN
  perform assert_verified_admin(p_caller);  -- P0.5
  SELECT role INTO caller_role FROM admins WHERE uid = p_caller AND is_active = true LIMIT 1;
  IF caller_role IS NULL OR caller_role NOT IN ('superadmin','admin') THEN
    RAISE EXCEPTION 'Access denied';
  END IF;
  UPDATE coaching_admins SET is_active = p_active WHERE uid = p_target_uid;
END;
$function$;

commit;
